spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
  datasource:
    jdbc-url: jdbc:h2:mem:devprimarydb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
data:
  userFile: /etc/passwd
  groupFile: /etc/group
